services:
  mysql:
    image: mysql:8.0
    container_name: vehicle_inventory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vehicle_inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
